### ISSUE TITLE
--show-toc is not working

### ISSUE THREAD

**Issue by Aneeqasif** [HareInWeed/pdf-toc#3]
i am trying to show toc but i am getting this error

```bash
❯ pdf-toc --show-toc toc file.pdf
Traceback (most recent call last):
  File "/home/aneeq/.local/bin/pdf-toc", line 33, in <module>
    sys.exit(load_entry_point('pdf-toc==1.1.3', 'console_scripts', 'pdf-toc')())
  File "/home/aneeq/.local/lib/python3.10/site-packages/src/main.py", line 169, in main
    toc = source.getToC(False)
AttributeError: 'Document' object has no attribute 'getToC'. Did you mean: 'get_oc'?
```

**Comment by HareInWeed** [comment]
I think this is because PyMuPDF has changed the method name of `Document.getToC` into `Document.get_toc`, as the [manual](https://pymupdf.readthedocs.io/en/latest/znames.html?highlight=getToC#deprecated-names) says.

I will release a new version of pdf-toc to fix the issue as soon as I have some spare time. For now, you can manually downgrade the PyMuPDF to an older version. `PyMuPDF == 1.18.15` should be working.

**Comment by Mia-Dan** [comment]
When I try using PyMuPDF==1.18.15, the `'Document' object has no attribute 'getToC'` error disappears, but another error occurs. Is there anything I can do with that?
```
Traceback (most recent call last):
  File "/opt/anaconda3/envs/sklearn_38/bin/pdf-toc", line 5, in <module>
    from src.main import main
  File "/opt/anaconda3/envs/sklearn_38/lib/python3.8/site-packages/src/__init__.py", line 1, in <module>
    from .main import main
  File "/opt/anaconda3/envs/sklearn_38/lib/python3.8/site-packages/src/main.py", line 6, in <module>
    import fitz
  File "/opt/anaconda3/envs/sklearn_38/lib/python3.8/site-packages/fitz/__init__.py", line 10, in <module>
    from fitz.fitz import *
  File "/opt/anaconda3/envs/sklearn_38/lib/python3.8/site-packages/fitz/fitz.py", line 15, in <module>
    from . import _fitz
ImportError: dlopen(/opt/anaconda3/envs/sklearn_38/lib/python3.8/site-packages/fitz/_fitz.cpython-38-darwin.so, 2): Symbol not found: ____chkstk_darwin
  Referenced from: /opt/anaconda3/envs/sklearn_38/lib/python3.8/site-packages/fitz/_fitz.cpython-38-darwin.so
  Expected in: /usr/lib/libSystem.B.dylib
 in /opt/anaconda3/envs/sklearn_38/lib/python3.8/site-packages/fitz/_fitz.cpython-38-darwin.so
```

**Comment by HareInWeed** [comment]
> When I try using PyMuPDF==1.18.15, the `'Document' object has no attribute 'getToC'` error disappears, but another error occurs. Is there anything I can do with that?
> 
> ```
> Traceback (most recent call last):
>   File "/opt/anaconda3/envs/sklearn_38/bin/pdf-toc", line 5, in <module>
>     from src.main import main
>   File "/opt/anaconda3/envs/sklearn_38/lib/python3.8/site-packages/src/__init__.py", line 1, in <module>
>     from .main import main
>   File "/opt/anaconda3/envs/sklearn_38/lib/python3.8/site-packages/src/main.py", line 6, in <module>
>     import fitz
>   File "/opt/anaconda3/envs/sklearn_38/lib/python3.8/site-packages/fitz/__init__.py", line 10, in <module>
>     from fitz.fitz import *
>   File "/opt/anaconda3/envs/sklearn_38/lib/python3.8/site-packages/fitz/fitz.py", line 15, in <module>
>     from . import _fitz
> ImportError: dlopen(/opt/anaconda3/envs/sklearn_38/lib/python3.8/site-packages/fitz/_fitz.cpython-38-darwin.so, 2): Symbol not found: ____chkstk_darwin
>   Referenced from: /opt/anaconda3/envs/sklearn_38/lib/python3.8/site-packages/fitz/_fitz.cpython-38-darwin.so
>   Expected in: /usr/lib/libSystem.B.dylib
>  in /opt/anaconda3/envs/sklearn_38/lib/python3.8/site-packages/fitz/_fitz.cpython-38-darwin.so
> ```

I am not sure what exactly happened here. It seems to be an upstream issue where PyMuPDF is not installed correctly. <https://github.com/pymupdf/PyMuPDF/issues/1296> could be related. You can try to reinstall PyMuPDF or update pip before installation.

This could be specific to some older versions of PyMuPDF through. Perhaps the issue will be resolved automatically in the upcoming version of pdf-toc. Let me know if the problem persists then.

**Comment by Mia-Dan** [comment]
Thanks for your help, unfortunately updating pip and reinstalling PyMuPDF didn't fix the issue. Anyway, I'm watching for the upcoming version of pdf-toc. ;)

**Comment by HareInWeed** [comment]
fixed in 815e20b
